
namespace SchoolManagementSystem
{
    partial class Dashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Dashboard));
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.sidepanel = new System.Windows.Forms.Panel();
            this.desBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.feeBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.resultsBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.secBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.classesBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.subjectBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.atdBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.stdBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.staffBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.homeBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.miniBtn = new System.Windows.Forms.PictureBox();
            this.aboutBtn = new System.Windows.Forms.PictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.maxiBtn = new System.Windows.Forms.PictureBox();
            this.resBtn = new System.Windows.Forms.PictureBox();
            this.closehoverBtn = new System.Windows.Forms.PictureBox();
            this.panelHome = new Bunifu.UI.WinForms.BunifuPanel();
            this.sidepanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bunifuGradientPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.miniBtn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.aboutBtn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.maxiBtn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.resBtn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.closehoverBtn)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // sidepanel
            // 
            this.sidepanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.sidepanel.Controls.Add(this.desBtn);
            this.sidepanel.Controls.Add(this.feeBtn);
            this.sidepanel.Controls.Add(this.resultsBtn);
            this.sidepanel.Controls.Add(this.secBtn);
            this.sidepanel.Controls.Add(this.classesBtn);
            this.sidepanel.Controls.Add(this.subjectBtn);
            this.sidepanel.Controls.Add(this.pictureBox1);
            this.sidepanel.Controls.Add(this.atdBtn);
            this.sidepanel.Controls.Add(this.stdBtn);
            this.sidepanel.Controls.Add(this.staffBtn);
            this.sidepanel.Controls.Add(this.homeBtn);
            this.sidepanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.sidepanel.Location = new System.Drawing.Point(0, 0);
            this.sidepanel.Name = "sidepanel";
            this.sidepanel.Size = new System.Drawing.Size(180, 600);
            this.sidepanel.TabIndex = 1;
            // 
            // desBtn
            // 
            this.desBtn.AllowAnimations = true;
            this.desBtn.AllowMouseEffects = true;
            this.desBtn.AllowToggling = false;
            this.desBtn.AnimationSpeed = 200;
            this.desBtn.AutoGenerateColors = false;
            this.desBtn.AutoRoundBorders = false;
            this.desBtn.AutoSizeLeftIcon = true;
            this.desBtn.AutoSizeRightIcon = true;
            this.desBtn.BackColor = System.Drawing.Color.Transparent;
            this.desBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.desBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("desBtn.BackgroundImage")));
            this.desBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.desBtn.ButtonText = "Staff Designation";
            this.desBtn.ButtonTextMarginLeft = 0;
            this.desBtn.ColorContrastOnClick = 45;
            this.desBtn.ColorContrastOnHover = 45;
            this.desBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.desBtn.CustomizableEdges = borderEdges1;
            this.desBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.desBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.desBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.desBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.desBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.desBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.desBtn.ForeColor = System.Drawing.Color.Black;
            this.desBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.desBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.desBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.desBtn.IconMarginLeft = 11;
            this.desBtn.IconPadding = 10;
            this.desBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.desBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.desBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.desBtn.IconSize = 25;
            this.desBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.desBtn.IdleBorderRadius = 35;
            this.desBtn.IdleBorderThickness = 1;
            this.desBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.desBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("desBtn.IdleIconLeftImage")));
            this.desBtn.IdleIconRightImage = null;
            this.desBtn.IndicateFocus = false;
            this.desBtn.Location = new System.Drawing.Point(-18, 531);
            this.desBtn.Name = "desBtn";
            this.desBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.desBtn.OnDisabledState.BorderRadius = 35;
            this.desBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.desBtn.OnDisabledState.BorderThickness = 1;
            this.desBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.desBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.desBtn.OnDisabledState.IconLeftImage = null;
            this.desBtn.OnDisabledState.IconRightImage = null;
            this.desBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.desBtn.onHoverState.BorderRadius = 35;
            this.desBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.desBtn.onHoverState.BorderThickness = 1;
            this.desBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.desBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.desBtn.onHoverState.IconLeftImage = null;
            this.desBtn.onHoverState.IconRightImage = null;
            this.desBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.desBtn.OnIdleState.BorderRadius = 35;
            this.desBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.desBtn.OnIdleState.BorderThickness = 1;
            this.desBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.desBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.desBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("desBtn.OnIdleState.IconLeftImage")));
            this.desBtn.OnIdleState.IconRightImage = null;
            this.desBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.desBtn.OnPressedState.BorderRadius = 35;
            this.desBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.desBtn.OnPressedState.BorderThickness = 1;
            this.desBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.desBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.desBtn.OnPressedState.IconLeftImage = null;
            this.desBtn.OnPressedState.IconRightImage = null;
            this.desBtn.Size = new System.Drawing.Size(175, 39);
            this.desBtn.TabIndex = 9;
            this.desBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.desBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.desBtn.TextMarginLeft = 0;
            this.desBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.desBtn.UseDefaultRadiusAndThickness = true;
            this.desBtn.Click += new System.EventHandler(this.desBtn_Click);
            // 
            // feeBtn
            // 
            this.feeBtn.AllowAnimations = true;
            this.feeBtn.AllowMouseEffects = true;
            this.feeBtn.AllowToggling = false;
            this.feeBtn.AnimationSpeed = 200;
            this.feeBtn.AutoGenerateColors = false;
            this.feeBtn.AutoRoundBorders = false;
            this.feeBtn.AutoSizeLeftIcon = true;
            this.feeBtn.AutoSizeRightIcon = true;
            this.feeBtn.BackColor = System.Drawing.Color.Transparent;
            this.feeBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.feeBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("feeBtn.BackgroundImage")));
            this.feeBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.feeBtn.ButtonText = "Fees";
            this.feeBtn.ButtonTextMarginLeft = 0;
            this.feeBtn.ColorContrastOnClick = 45;
            this.feeBtn.ColorContrastOnHover = 45;
            this.feeBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.feeBtn.CustomizableEdges = borderEdges2;
            this.feeBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.feeBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.feeBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.feeBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.feeBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.feeBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.feeBtn.ForeColor = System.Drawing.Color.Black;
            this.feeBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.feeBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.feeBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.feeBtn.IconMarginLeft = 11;
            this.feeBtn.IconPadding = 10;
            this.feeBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.feeBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.feeBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.feeBtn.IconSize = 25;
            this.feeBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.feeBtn.IdleBorderRadius = 35;
            this.feeBtn.IdleBorderThickness = 1;
            this.feeBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.feeBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("feeBtn.IdleIconLeftImage")));
            this.feeBtn.IdleIconRightImage = null;
            this.feeBtn.IndicateFocus = false;
            this.feeBtn.Location = new System.Drawing.Point(-18, 485);
            this.feeBtn.Name = "feeBtn";
            this.feeBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.feeBtn.OnDisabledState.BorderRadius = 35;
            this.feeBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.feeBtn.OnDisabledState.BorderThickness = 1;
            this.feeBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.feeBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.feeBtn.OnDisabledState.IconLeftImage = null;
            this.feeBtn.OnDisabledState.IconRightImage = null;
            this.feeBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.feeBtn.onHoverState.BorderRadius = 35;
            this.feeBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.feeBtn.onHoverState.BorderThickness = 1;
            this.feeBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.feeBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.feeBtn.onHoverState.IconLeftImage = null;
            this.feeBtn.onHoverState.IconRightImage = null;
            this.feeBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.feeBtn.OnIdleState.BorderRadius = 35;
            this.feeBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.feeBtn.OnIdleState.BorderThickness = 1;
            this.feeBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.feeBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.feeBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("feeBtn.OnIdleState.IconLeftImage")));
            this.feeBtn.OnIdleState.IconRightImage = null;
            this.feeBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.feeBtn.OnPressedState.BorderRadius = 35;
            this.feeBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.feeBtn.OnPressedState.BorderThickness = 1;
            this.feeBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.feeBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.feeBtn.OnPressedState.IconLeftImage = null;
            this.feeBtn.OnPressedState.IconRightImage = null;
            this.feeBtn.Size = new System.Drawing.Size(175, 39);
            this.feeBtn.TabIndex = 8;
            this.feeBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.feeBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.feeBtn.TextMarginLeft = 0;
            this.feeBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.feeBtn.UseDefaultRadiusAndThickness = true;
            this.feeBtn.Click += new System.EventHandler(this.feeBtn_Click);
            // 
            // resultsBtn
            // 
            this.resultsBtn.AllowAnimations = true;
            this.resultsBtn.AllowMouseEffects = true;
            this.resultsBtn.AllowToggling = false;
            this.resultsBtn.AnimationSpeed = 200;
            this.resultsBtn.AutoGenerateColors = false;
            this.resultsBtn.AutoRoundBorders = false;
            this.resultsBtn.AutoSizeLeftIcon = true;
            this.resultsBtn.AutoSizeRightIcon = true;
            this.resultsBtn.BackColor = System.Drawing.Color.Transparent;
            this.resultsBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.resultsBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("resultsBtn.BackgroundImage")));
            this.resultsBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resultsBtn.ButtonText = "Results";
            this.resultsBtn.ButtonTextMarginLeft = 0;
            this.resultsBtn.ColorContrastOnClick = 45;
            this.resultsBtn.ColorContrastOnHover = 45;
            this.resultsBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.resultsBtn.CustomizableEdges = borderEdges3;
            this.resultsBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.resultsBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.resultsBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.resultsBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.resultsBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.resultsBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.resultsBtn.ForeColor = System.Drawing.Color.Black;
            this.resultsBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.resultsBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.resultsBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.resultsBtn.IconMarginLeft = 11;
            this.resultsBtn.IconPadding = 10;
            this.resultsBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.resultsBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.resultsBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.resultsBtn.IconSize = 30;
            this.resultsBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.resultsBtn.IdleBorderRadius = 35;
            this.resultsBtn.IdleBorderThickness = 1;
            this.resultsBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.resultsBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("resultsBtn.IdleIconLeftImage")));
            this.resultsBtn.IdleIconRightImage = null;
            this.resultsBtn.IndicateFocus = false;
            this.resultsBtn.Location = new System.Drawing.Point(-18, 439);
            this.resultsBtn.Name = "resultsBtn";
            this.resultsBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.resultsBtn.OnDisabledState.BorderRadius = 35;
            this.resultsBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resultsBtn.OnDisabledState.BorderThickness = 1;
            this.resultsBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.resultsBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.resultsBtn.OnDisabledState.IconLeftImage = null;
            this.resultsBtn.OnDisabledState.IconRightImage = null;
            this.resultsBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.resultsBtn.onHoverState.BorderRadius = 35;
            this.resultsBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resultsBtn.onHoverState.BorderThickness = 1;
            this.resultsBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.resultsBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.resultsBtn.onHoverState.IconLeftImage = null;
            this.resultsBtn.onHoverState.IconRightImage = null;
            this.resultsBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.resultsBtn.OnIdleState.BorderRadius = 35;
            this.resultsBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resultsBtn.OnIdleState.BorderThickness = 1;
            this.resultsBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.resultsBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.resultsBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resultsBtn.OnIdleState.IconLeftImage")));
            this.resultsBtn.OnIdleState.IconRightImage = null;
            this.resultsBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.resultsBtn.OnPressedState.BorderRadius = 35;
            this.resultsBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.resultsBtn.OnPressedState.BorderThickness = 1;
            this.resultsBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.resultsBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.resultsBtn.OnPressedState.IconLeftImage = null;
            this.resultsBtn.OnPressedState.IconRightImage = null;
            this.resultsBtn.Size = new System.Drawing.Size(175, 39);
            this.resultsBtn.TabIndex = 7;
            this.resultsBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.resultsBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.resultsBtn.TextMarginLeft = 0;
            this.resultsBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.resultsBtn.UseDefaultRadiusAndThickness = true;
            this.resultsBtn.Click += new System.EventHandler(this.resultsBtn_Click);
            // 
            // secBtn
            // 
            this.secBtn.AllowAnimations = true;
            this.secBtn.AllowMouseEffects = true;
            this.secBtn.AllowToggling = false;
            this.secBtn.AnimationSpeed = 200;
            this.secBtn.AutoGenerateColors = false;
            this.secBtn.AutoRoundBorders = false;
            this.secBtn.AutoSizeLeftIcon = true;
            this.secBtn.AutoSizeRightIcon = true;
            this.secBtn.BackColor = System.Drawing.Color.Transparent;
            this.secBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.secBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("secBtn.BackgroundImage")));
            this.secBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.secBtn.ButtonText = "Sections";
            this.secBtn.ButtonTextMarginLeft = 0;
            this.secBtn.ColorContrastOnClick = 45;
            this.secBtn.ColorContrastOnHover = 45;
            this.secBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.secBtn.CustomizableEdges = borderEdges4;
            this.secBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.secBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.secBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.secBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.secBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.secBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.secBtn.ForeColor = System.Drawing.Color.Black;
            this.secBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.secBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.secBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.secBtn.IconMarginLeft = 11;
            this.secBtn.IconPadding = 10;
            this.secBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.secBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.secBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.secBtn.IconSize = 25;
            this.secBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.secBtn.IdleBorderRadius = 35;
            this.secBtn.IdleBorderThickness = 1;
            this.secBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.secBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("secBtn.IdleIconLeftImage")));
            this.secBtn.IdleIconRightImage = null;
            this.secBtn.IndicateFocus = false;
            this.secBtn.Location = new System.Drawing.Point(-18, 393);
            this.secBtn.Name = "secBtn";
            this.secBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.secBtn.OnDisabledState.BorderRadius = 35;
            this.secBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.secBtn.OnDisabledState.BorderThickness = 1;
            this.secBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.secBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.secBtn.OnDisabledState.IconLeftImage = null;
            this.secBtn.OnDisabledState.IconRightImage = null;
            this.secBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.secBtn.onHoverState.BorderRadius = 35;
            this.secBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.secBtn.onHoverState.BorderThickness = 1;
            this.secBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.secBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.secBtn.onHoverState.IconLeftImage = null;
            this.secBtn.onHoverState.IconRightImage = null;
            this.secBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.secBtn.OnIdleState.BorderRadius = 35;
            this.secBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.secBtn.OnIdleState.BorderThickness = 1;
            this.secBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.secBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.secBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("secBtn.OnIdleState.IconLeftImage")));
            this.secBtn.OnIdleState.IconRightImage = null;
            this.secBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.secBtn.OnPressedState.BorderRadius = 35;
            this.secBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.secBtn.OnPressedState.BorderThickness = 1;
            this.secBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.secBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.secBtn.OnPressedState.IconLeftImage = null;
            this.secBtn.OnPressedState.IconRightImage = null;
            this.secBtn.Size = new System.Drawing.Size(175, 39);
            this.secBtn.TabIndex = 6;
            this.secBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.secBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.secBtn.TextMarginLeft = 0;
            this.secBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.secBtn.UseDefaultRadiusAndThickness = true;
            this.secBtn.Click += new System.EventHandler(this.secBtn_Click);
            // 
            // classesBtn
            // 
            this.classesBtn.AllowAnimations = true;
            this.classesBtn.AllowMouseEffects = true;
            this.classesBtn.AllowToggling = false;
            this.classesBtn.AnimationSpeed = 200;
            this.classesBtn.AutoGenerateColors = false;
            this.classesBtn.AutoRoundBorders = false;
            this.classesBtn.AutoSizeLeftIcon = true;
            this.classesBtn.AutoSizeRightIcon = true;
            this.classesBtn.BackColor = System.Drawing.Color.Transparent;
            this.classesBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.classesBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("classesBtn.BackgroundImage")));
            this.classesBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.classesBtn.ButtonText = "Classes";
            this.classesBtn.ButtonTextMarginLeft = 0;
            this.classesBtn.ColorContrastOnClick = 45;
            this.classesBtn.ColorContrastOnHover = 45;
            this.classesBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.classesBtn.CustomizableEdges = borderEdges5;
            this.classesBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.classesBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.classesBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.classesBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.classesBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.classesBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.classesBtn.ForeColor = System.Drawing.Color.Black;
            this.classesBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.classesBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.classesBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.classesBtn.IconMarginLeft = 11;
            this.classesBtn.IconPadding = 10;
            this.classesBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.classesBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.classesBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.classesBtn.IconSize = 25;
            this.classesBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.classesBtn.IdleBorderRadius = 35;
            this.classesBtn.IdleBorderThickness = 1;
            this.classesBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.classesBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("classesBtn.IdleIconLeftImage")));
            this.classesBtn.IdleIconRightImage = null;
            this.classesBtn.IndicateFocus = false;
            this.classesBtn.Location = new System.Drawing.Point(-18, 347);
            this.classesBtn.Name = "classesBtn";
            this.classesBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.classesBtn.OnDisabledState.BorderRadius = 35;
            this.classesBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.classesBtn.OnDisabledState.BorderThickness = 1;
            this.classesBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.classesBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.classesBtn.OnDisabledState.IconLeftImage = null;
            this.classesBtn.OnDisabledState.IconRightImage = null;
            this.classesBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.classesBtn.onHoverState.BorderRadius = 35;
            this.classesBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.classesBtn.onHoverState.BorderThickness = 1;
            this.classesBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.classesBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.classesBtn.onHoverState.IconLeftImage = null;
            this.classesBtn.onHoverState.IconRightImage = null;
            this.classesBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.classesBtn.OnIdleState.BorderRadius = 35;
            this.classesBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.classesBtn.OnIdleState.BorderThickness = 1;
            this.classesBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.classesBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.classesBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("classesBtn.OnIdleState.IconLeftImage")));
            this.classesBtn.OnIdleState.IconRightImage = null;
            this.classesBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.classesBtn.OnPressedState.BorderRadius = 35;
            this.classesBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.classesBtn.OnPressedState.BorderThickness = 1;
            this.classesBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.classesBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.classesBtn.OnPressedState.IconLeftImage = null;
            this.classesBtn.OnPressedState.IconRightImage = null;
            this.classesBtn.Size = new System.Drawing.Size(175, 39);
            this.classesBtn.TabIndex = 5;
            this.classesBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.classesBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.classesBtn.TextMarginLeft = 0;
            this.classesBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.classesBtn.UseDefaultRadiusAndThickness = true;
            this.classesBtn.Click += new System.EventHandler(this.classesBtn_Click);
            // 
            // subjectBtn
            // 
            this.subjectBtn.AllowAnimations = true;
            this.subjectBtn.AllowMouseEffects = true;
            this.subjectBtn.AllowToggling = false;
            this.subjectBtn.AnimationSpeed = 200;
            this.subjectBtn.AutoGenerateColors = false;
            this.subjectBtn.AutoRoundBorders = false;
            this.subjectBtn.AutoSizeLeftIcon = true;
            this.subjectBtn.AutoSizeRightIcon = true;
            this.subjectBtn.BackColor = System.Drawing.Color.Transparent;
            this.subjectBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.subjectBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("subjectBtn.BackgroundImage")));
            this.subjectBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.subjectBtn.ButtonText = "Subject";
            this.subjectBtn.ButtonTextMarginLeft = 0;
            this.subjectBtn.ColorContrastOnClick = 45;
            this.subjectBtn.ColorContrastOnHover = 45;
            this.subjectBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.subjectBtn.CustomizableEdges = borderEdges6;
            this.subjectBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.subjectBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.subjectBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.subjectBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.subjectBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.subjectBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.subjectBtn.ForeColor = System.Drawing.Color.Black;
            this.subjectBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.subjectBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.subjectBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.subjectBtn.IconMarginLeft = 11;
            this.subjectBtn.IconPadding = 10;
            this.subjectBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.subjectBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.subjectBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.subjectBtn.IconSize = 25;
            this.subjectBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.subjectBtn.IdleBorderRadius = 35;
            this.subjectBtn.IdleBorderThickness = 1;
            this.subjectBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.subjectBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("subjectBtn.IdleIconLeftImage")));
            this.subjectBtn.IdleIconRightImage = null;
            this.subjectBtn.IndicateFocus = false;
            this.subjectBtn.Location = new System.Drawing.Point(-18, 301);
            this.subjectBtn.Name = "subjectBtn";
            this.subjectBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.subjectBtn.OnDisabledState.BorderRadius = 35;
            this.subjectBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.subjectBtn.OnDisabledState.BorderThickness = 1;
            this.subjectBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.subjectBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.subjectBtn.OnDisabledState.IconLeftImage = null;
            this.subjectBtn.OnDisabledState.IconRightImage = null;
            this.subjectBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.subjectBtn.onHoverState.BorderRadius = 35;
            this.subjectBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.subjectBtn.onHoverState.BorderThickness = 1;
            this.subjectBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.subjectBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.subjectBtn.onHoverState.IconLeftImage = null;
            this.subjectBtn.onHoverState.IconRightImage = null;
            this.subjectBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.subjectBtn.OnIdleState.BorderRadius = 35;
            this.subjectBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.subjectBtn.OnIdleState.BorderThickness = 1;
            this.subjectBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.subjectBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.subjectBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("subjectBtn.OnIdleState.IconLeftImage")));
            this.subjectBtn.OnIdleState.IconRightImage = null;
            this.subjectBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.subjectBtn.OnPressedState.BorderRadius = 35;
            this.subjectBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.subjectBtn.OnPressedState.BorderThickness = 1;
            this.subjectBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.subjectBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.subjectBtn.OnPressedState.IconLeftImage = null;
            this.subjectBtn.OnPressedState.IconRightImage = null;
            this.subjectBtn.Size = new System.Drawing.Size(175, 39);
            this.subjectBtn.TabIndex = 4;
            this.subjectBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.subjectBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.subjectBtn.TextMarginLeft = 0;
            this.subjectBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.subjectBtn.UseDefaultRadiusAndThickness = true;
            this.subjectBtn.Click += new System.EventHandler(this.subjectBtn_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(25, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(132, 88);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 4;
            this.pictureBox1.TabStop = false;
            // 
            // atdBtn
            // 
            this.atdBtn.AllowAnimations = true;
            this.atdBtn.AllowMouseEffects = true;
            this.atdBtn.AllowToggling = false;
            this.atdBtn.AnimationSpeed = 200;
            this.atdBtn.AutoGenerateColors = false;
            this.atdBtn.AutoRoundBorders = false;
            this.atdBtn.AutoSizeLeftIcon = true;
            this.atdBtn.AutoSizeRightIcon = true;
            this.atdBtn.BackColor = System.Drawing.Color.Transparent;
            this.atdBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.atdBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("atdBtn.BackgroundImage")));
            this.atdBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.atdBtn.ButtonText = "Attendence";
            this.atdBtn.ButtonTextMarginLeft = 0;
            this.atdBtn.ColorContrastOnClick = 45;
            this.atdBtn.ColorContrastOnHover = 45;
            this.atdBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.atdBtn.CustomizableEdges = borderEdges7;
            this.atdBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.atdBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.atdBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.atdBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.atdBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.atdBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.atdBtn.ForeColor = System.Drawing.Color.Black;
            this.atdBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.atdBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.atdBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.atdBtn.IconMarginLeft = 11;
            this.atdBtn.IconPadding = 10;
            this.atdBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.atdBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.atdBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.atdBtn.IconSize = 25;
            this.atdBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.atdBtn.IdleBorderRadius = 35;
            this.atdBtn.IdleBorderThickness = 1;
            this.atdBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.atdBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("atdBtn.IdleIconLeftImage")));
            this.atdBtn.IdleIconRightImage = null;
            this.atdBtn.IndicateFocus = false;
            this.atdBtn.Location = new System.Drawing.Point(-18, 255);
            this.atdBtn.Name = "atdBtn";
            this.atdBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.atdBtn.OnDisabledState.BorderRadius = 35;
            this.atdBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.atdBtn.OnDisabledState.BorderThickness = 1;
            this.atdBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.atdBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.atdBtn.OnDisabledState.IconLeftImage = null;
            this.atdBtn.OnDisabledState.IconRightImage = null;
            this.atdBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.atdBtn.onHoverState.BorderRadius = 35;
            this.atdBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.atdBtn.onHoverState.BorderThickness = 1;
            this.atdBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.atdBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.atdBtn.onHoverState.IconLeftImage = null;
            this.atdBtn.onHoverState.IconRightImage = null;
            this.atdBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.atdBtn.OnIdleState.BorderRadius = 35;
            this.atdBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.atdBtn.OnIdleState.BorderThickness = 1;
            this.atdBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.atdBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.atdBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("atdBtn.OnIdleState.IconLeftImage")));
            this.atdBtn.OnIdleState.IconRightImage = null;
            this.atdBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.atdBtn.OnPressedState.BorderRadius = 35;
            this.atdBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.atdBtn.OnPressedState.BorderThickness = 1;
            this.atdBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.atdBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.atdBtn.OnPressedState.IconLeftImage = null;
            this.atdBtn.OnPressedState.IconRightImage = null;
            this.atdBtn.Size = new System.Drawing.Size(175, 39);
            this.atdBtn.TabIndex = 3;
            this.atdBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.atdBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.atdBtn.TextMarginLeft = 0;
            this.atdBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.atdBtn.UseDefaultRadiusAndThickness = true;
            this.atdBtn.Click += new System.EventHandler(this.atdBtn_Click);
            // 
            // stdBtn
            // 
            this.stdBtn.AllowAnimations = true;
            this.stdBtn.AllowMouseEffects = true;
            this.stdBtn.AllowToggling = false;
            this.stdBtn.AnimationSpeed = 200;
            this.stdBtn.AutoGenerateColors = false;
            this.stdBtn.AutoRoundBorders = false;
            this.stdBtn.AutoSizeLeftIcon = true;
            this.stdBtn.AutoSizeRightIcon = true;
            this.stdBtn.BackColor = System.Drawing.Color.Transparent;
            this.stdBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.stdBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("stdBtn.BackgroundImage")));
            this.stdBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.stdBtn.ButtonText = "Student";
            this.stdBtn.ButtonTextMarginLeft = 0;
            this.stdBtn.ColorContrastOnClick = 45;
            this.stdBtn.ColorContrastOnHover = 45;
            this.stdBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.stdBtn.CustomizableEdges = borderEdges8;
            this.stdBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.stdBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.stdBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.stdBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.stdBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.stdBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.stdBtn.ForeColor = System.Drawing.Color.Black;
            this.stdBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.stdBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.stdBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.stdBtn.IconMarginLeft = 11;
            this.stdBtn.IconPadding = 10;
            this.stdBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.stdBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.stdBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.stdBtn.IconSize = 25;
            this.stdBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.stdBtn.IdleBorderRadius = 35;
            this.stdBtn.IdleBorderThickness = 1;
            this.stdBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.stdBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("stdBtn.IdleIconLeftImage")));
            this.stdBtn.IdleIconRightImage = null;
            this.stdBtn.IndicateFocus = false;
            this.stdBtn.Location = new System.Drawing.Point(-18, 209);
            this.stdBtn.Name = "stdBtn";
            this.stdBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.stdBtn.OnDisabledState.BorderRadius = 35;
            this.stdBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.stdBtn.OnDisabledState.BorderThickness = 1;
            this.stdBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.stdBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.stdBtn.OnDisabledState.IconLeftImage = null;
            this.stdBtn.OnDisabledState.IconRightImage = null;
            this.stdBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.stdBtn.onHoverState.BorderRadius = 35;
            this.stdBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.stdBtn.onHoverState.BorderThickness = 1;
            this.stdBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.stdBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.stdBtn.onHoverState.IconLeftImage = null;
            this.stdBtn.onHoverState.IconRightImage = null;
            this.stdBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.stdBtn.OnIdleState.BorderRadius = 35;
            this.stdBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.stdBtn.OnIdleState.BorderThickness = 1;
            this.stdBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.stdBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.stdBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("stdBtn.OnIdleState.IconLeftImage")));
            this.stdBtn.OnIdleState.IconRightImage = null;
            this.stdBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.stdBtn.OnPressedState.BorderRadius = 35;
            this.stdBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.stdBtn.OnPressedState.BorderThickness = 1;
            this.stdBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.stdBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.stdBtn.OnPressedState.IconLeftImage = null;
            this.stdBtn.OnPressedState.IconRightImage = null;
            this.stdBtn.Size = new System.Drawing.Size(175, 39);
            this.stdBtn.TabIndex = 2;
            this.stdBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.stdBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.stdBtn.TextMarginLeft = 0;
            this.stdBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.stdBtn.UseDefaultRadiusAndThickness = true;
            this.stdBtn.Click += new System.EventHandler(this.stdBtn_Click);
            // 
            // staffBtn
            // 
            this.staffBtn.AllowAnimations = true;
            this.staffBtn.AllowMouseEffects = true;
            this.staffBtn.AllowToggling = false;
            this.staffBtn.AnimationSpeed = 200;
            this.staffBtn.AutoGenerateColors = false;
            this.staffBtn.AutoRoundBorders = false;
            this.staffBtn.AutoSizeLeftIcon = true;
            this.staffBtn.AutoSizeRightIcon = true;
            this.staffBtn.BackColor = System.Drawing.Color.Transparent;
            this.staffBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.staffBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("staffBtn.BackgroundImage")));
            this.staffBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.staffBtn.ButtonText = "Staff";
            this.staffBtn.ButtonTextMarginLeft = 0;
            this.staffBtn.ColorContrastOnClick = 45;
            this.staffBtn.ColorContrastOnHover = 45;
            this.staffBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.staffBtn.CustomizableEdges = borderEdges9;
            this.staffBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.staffBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.staffBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.staffBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.staffBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.staffBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.staffBtn.ForeColor = System.Drawing.Color.Black;
            this.staffBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.staffBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.staffBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.staffBtn.IconMarginLeft = 11;
            this.staffBtn.IconPadding = 10;
            this.staffBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.staffBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.staffBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.staffBtn.IconSize = 25;
            this.staffBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.staffBtn.IdleBorderRadius = 35;
            this.staffBtn.IdleBorderThickness = 1;
            this.staffBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.staffBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("staffBtn.IdleIconLeftImage")));
            this.staffBtn.IdleIconRightImage = null;
            this.staffBtn.IndicateFocus = false;
            this.staffBtn.Location = new System.Drawing.Point(-18, 163);
            this.staffBtn.Name = "staffBtn";
            this.staffBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.staffBtn.OnDisabledState.BorderRadius = 35;
            this.staffBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.staffBtn.OnDisabledState.BorderThickness = 1;
            this.staffBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.staffBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.staffBtn.OnDisabledState.IconLeftImage = null;
            this.staffBtn.OnDisabledState.IconRightImage = null;
            this.staffBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.staffBtn.onHoverState.BorderRadius = 35;
            this.staffBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.staffBtn.onHoverState.BorderThickness = 1;
            this.staffBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.staffBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.staffBtn.onHoverState.IconLeftImage = null;
            this.staffBtn.onHoverState.IconRightImage = null;
            this.staffBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.staffBtn.OnIdleState.BorderRadius = 35;
            this.staffBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.staffBtn.OnIdleState.BorderThickness = 1;
            this.staffBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.staffBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.staffBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("staffBtn.OnIdleState.IconLeftImage")));
            this.staffBtn.OnIdleState.IconRightImage = null;
            this.staffBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.staffBtn.OnPressedState.BorderRadius = 35;
            this.staffBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.staffBtn.OnPressedState.BorderThickness = 1;
            this.staffBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.staffBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.staffBtn.OnPressedState.IconLeftImage = null;
            this.staffBtn.OnPressedState.IconRightImage = null;
            this.staffBtn.Size = new System.Drawing.Size(175, 39);
            this.staffBtn.TabIndex = 1;
            this.staffBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.staffBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.staffBtn.TextMarginLeft = 0;
            this.staffBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.staffBtn.UseDefaultRadiusAndThickness = true;
            this.staffBtn.Click += new System.EventHandler(this.staffBtn_Click);
            // 
            // homeBtn
            // 
            this.homeBtn.AllowAnimations = true;
            this.homeBtn.AllowMouseEffects = true;
            this.homeBtn.AllowToggling = false;
            this.homeBtn.AnimationSpeed = 200;
            this.homeBtn.AutoGenerateColors = false;
            this.homeBtn.AutoRoundBorders = false;
            this.homeBtn.AutoSizeLeftIcon = true;
            this.homeBtn.AutoSizeRightIcon = true;
            this.homeBtn.BackColor = System.Drawing.Color.Transparent;
            this.homeBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.homeBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("homeBtn.BackgroundImage")));
            this.homeBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.ButtonText = "Home";
            this.homeBtn.ButtonTextMarginLeft = 0;
            this.homeBtn.ColorContrastOnClick = 45;
            this.homeBtn.ColorContrastOnHover = 45;
            this.homeBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.homeBtn.CustomizableEdges = borderEdges10;
            this.homeBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.homeBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.homeBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.homeBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.homeBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.homeBtn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.homeBtn.ForeColor = System.Drawing.Color.Black;
            this.homeBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.homeBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.homeBtn.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.homeBtn.IconMarginLeft = 11;
            this.homeBtn.IconPadding = 10;
            this.homeBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.homeBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.homeBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.homeBtn.IconSize = 25;
            this.homeBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.homeBtn.IdleBorderRadius = 35;
            this.homeBtn.IdleBorderThickness = 1;
            this.homeBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.homeBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("homeBtn.IdleIconLeftImage")));
            this.homeBtn.IdleIconRightImage = null;
            this.homeBtn.IndicateFocus = false;
            this.homeBtn.Location = new System.Drawing.Point(-18, 117);
            this.homeBtn.Name = "homeBtn";
            this.homeBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.homeBtn.OnDisabledState.BorderRadius = 35;
            this.homeBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.OnDisabledState.BorderThickness = 1;
            this.homeBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.homeBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.homeBtn.OnDisabledState.IconLeftImage = null;
            this.homeBtn.OnDisabledState.IconRightImage = null;
            this.homeBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.homeBtn.onHoverState.BorderRadius = 35;
            this.homeBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.onHoverState.BorderThickness = 1;
            this.homeBtn.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.homeBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.homeBtn.onHoverState.IconLeftImage = null;
            this.homeBtn.onHoverState.IconRightImage = null;
            this.homeBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.homeBtn.OnIdleState.BorderRadius = 35;
            this.homeBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.OnIdleState.BorderThickness = 1;
            this.homeBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.homeBtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.homeBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("homeBtn.OnIdleState.IconLeftImage")));
            this.homeBtn.OnIdleState.IconRightImage = null;
            this.homeBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.homeBtn.OnPressedState.BorderRadius = 35;
            this.homeBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.OnPressedState.BorderThickness = 1;
            this.homeBtn.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.homeBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.homeBtn.OnPressedState.IconLeftImage = null;
            this.homeBtn.OnPressedState.IconRightImage = null;
            this.homeBtn.Size = new System.Drawing.Size(175, 39);
            this.homeBtn.TabIndex = 0;
            this.homeBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.homeBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.homeBtn.TextMarginLeft = 0;
            this.homeBtn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.homeBtn.UseDefaultRadiusAndThickness = true;
            this.homeBtn.Click += new System.EventHandler(this.homeBtn_Click);
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.miniBtn);
            this.bunifuGradientPanel1.Controls.Add(this.aboutBtn);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuGradientPanel1.Controls.Add(this.maxiBtn);
            this.bunifuGradientPanel1.Controls.Add(this.resBtn);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.SystemColors.Control;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(158)))), ((int)(((byte)(235)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.SystemColors.Control;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(180, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(820, 49);
            this.bunifuGradientPanel1.TabIndex = 2;
            this.bunifuGradientPanel1.DoubleClick += new System.EventHandler(this.bunifuGradientPanel1_DoubleClick);
            this.bunifuGradientPanel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.bunifuGradientPanel1_MouseDown);
            this.bunifuGradientPanel1.MouseMove += new System.Windows.Forms.MouseEventHandler(this.bunifuGradientPanel1_MouseMove);
            this.bunifuGradientPanel1.MouseUp += new System.Windows.Forms.MouseEventHandler(this.bunifuGradientPanel1_MouseUp);
            // 
            // miniBtn
            // 
            this.miniBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.miniBtn.Image = ((System.Drawing.Image)(resources.GetObject("miniBtn.Image")));
            this.miniBtn.Location = new System.Drawing.Point(701, 11);
            this.miniBtn.Name = "miniBtn";
            this.miniBtn.Size = new System.Drawing.Size(30, 30);
            this.miniBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.miniBtn.TabIndex = 10;
            this.miniBtn.TabStop = false;
            this.miniBtn.Click += new System.EventHandler(this.miniBtn_Click);
            // 
            // aboutBtn
            // 
            this.aboutBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.aboutBtn.Image = ((System.Drawing.Image)(resources.GetObject("aboutBtn.Image")));
            this.aboutBtn.Location = new System.Drawing.Point(665, 11);
            this.aboutBtn.Name = "aboutBtn";
            this.aboutBtn.Size = new System.Drawing.Size(30, 30);
            this.aboutBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.aboutBtn.TabIndex = 0;
            this.aboutBtn.TabStop = false;
            this.aboutBtn.Click += new System.EventHandler(this.aboutBtn_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel1.Location = new System.Drawing.Point(17, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(220, 19);
            this.bunifuLabel1.TabIndex = 8;
            this.bunifuLabel1.Text = "School Management System";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // maxiBtn
            // 
            this.maxiBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.maxiBtn.Image = ((System.Drawing.Image)(resources.GetObject("maxiBtn.Image")));
            this.maxiBtn.Location = new System.Drawing.Point(737, 11);
            this.maxiBtn.Name = "maxiBtn";
            this.maxiBtn.Size = new System.Drawing.Size(30, 30);
            this.maxiBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.maxiBtn.TabIndex = 9;
            this.maxiBtn.TabStop = false;
            this.maxiBtn.Click += new System.EventHandler(this.maxiBtn_Click);
            // 
            // resBtn
            // 
            this.resBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.resBtn.Image = ((System.Drawing.Image)(resources.GetObject("resBtn.Image")));
            this.resBtn.Location = new System.Drawing.Point(737, 11);
            this.resBtn.Name = "resBtn";
            this.resBtn.Size = new System.Drawing.Size(30, 30);
            this.resBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.resBtn.TabIndex = 11;
            this.resBtn.TabStop = false;
            this.resBtn.Visible = false;
            this.resBtn.Click += new System.EventHandler(this.resBtn_Click_1);
            // 
            // closehoverBtn
            // 
            this.closehoverBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.closehoverBtn.Image = ((System.Drawing.Image)(resources.GetObject("closehoverBtn.Image")));
            this.closehoverBtn.Location = new System.Drawing.Point(953, 11);
            this.closehoverBtn.Name = "closehoverBtn";
            this.closehoverBtn.Size = new System.Drawing.Size(30, 30);
            this.closehoverBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.closehoverBtn.TabIndex = 12;
            this.closehoverBtn.TabStop = false;
            this.closehoverBtn.Click += new System.EventHandler(this.closehoverBtn_Click_1);
            // 
            // panelHome
            // 
            this.panelHome.BackgroundColor = System.Drawing.Color.Transparent;
            this.panelHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelHome.BackgroundImage")));
            this.panelHome.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelHome.BorderColor = System.Drawing.Color.Transparent;
            this.panelHome.BorderRadius = 35;
            this.panelHome.BorderThickness = 1;
            this.panelHome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelHome.Location = new System.Drawing.Point(180, 49);
            this.panelHome.Name = "panelHome";
            this.panelHome.ShowBorders = true;
            this.panelHome.Size = new System.Drawing.Size(820, 551);
            this.panelHome.TabIndex = 13;
            // 
            // Dashboard
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.ClientSize = new System.Drawing.Size(1000, 600);
            this.Controls.Add(this.panelHome);
            this.Controls.Add(this.closehoverBtn);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Controls.Add(this.sidepanel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Dashboard";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "School Management System";
            this.sidepanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.miniBtn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.aboutBtn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.maxiBtn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.resBtn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.closehoverBtn)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.Panel sidepanel;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton atdBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton stdBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton staffBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton homeBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton desBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton feeBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton resultsBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton secBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton classesBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton subjectBtn;
        private Bunifu.UI.WinForms.BunifuPanel panelHome;
        private System.Windows.Forms.PictureBox resBtn;
        private System.Windows.Forms.PictureBox miniBtn;
        private System.Windows.Forms.PictureBox maxiBtn;
        private System.Windows.Forms.PictureBox closehoverBtn;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.PictureBox aboutBtn;
    }
}

